class UserData {
  static String? accessToken;
  static String? fcmToken;
  static int? id;
  static String? designation;
  static String? userId;
  static String? employeeId;
  static String? email;
  static String? username;
  static String? name;
  static String? phone;
  static String? emargencyContact;
  static String? address;
  static String? photo;
  static String? url;
  static String? imagePath;
  static String? checkIn;
  static String? checkOut;
}